2017-12-24 21:00:55,276 - DaoDecorator - 7156 - ERROR - read - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\core\DaoDecorator.py", line 25, in read
    sql = UserSQLMapper().getSQL(self.function)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\mapping\UserMapper.py", line 7, in __init__
    self.data.setdefault("addUser",self.__setSQL().addUserSQL)
AttributeError: 'NoneType' object has no attribute 'addUserSQL'

2017-12-24 21:04:22,223 - DaoDecorator - 6796 - ERROR - read - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\core\DaoDecorator.py", line 31, in read
    return DbBaseHelper().read(sql,self.data)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseHelper.py", line 21, in read
    db = Connection(autocommit=False)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 32, in __init__
    self.reconnect(**dbinfo)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 67, in reconnect
    self._conn = self._get_connection(**kwargs)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 70, in _get_connection
    return MySQLdb.connect(cursorclass=MySQLdb.cursors.DictCursor, charset = 'utf8', **kwargs)
  File "c:\users\jessica\appdata\local\temp\easy_install-qvdkaj\MySQL_python-1.2.5-py2.7-win32.egg.tmp\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "c:\users\jessica\appdata\local\temp\easy_install-qvdkaj\MySQL_python-1.2.5-py2.7-win32.egg.tmp\MySQLdb\connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on 'localhost' (10061)")

2017-12-24 21:05:03,006 - DaoDecorator - 6796 - ERROR - read - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\core\DaoDecorator.py", line 31, in read
    return DbBaseHelper().read(sql,self.data)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseHelper.py", line 21, in read
    db = Connection(autocommit=False)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 32, in __init__
    self.reconnect(**dbinfo)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 67, in reconnect
    self._conn = self._get_connection(**kwargs)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 70, in _get_connection
    return MySQLdb.connect(cursorclass=MySQLdb.cursors.DictCursor, charset = 'utf8', **kwargs)
  File "c:\users\jessica\appdata\local\temp\easy_install-qvdkaj\MySQL_python-1.2.5-py2.7-win32.egg.tmp\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "c:\users\jessica\appdata\local\temp\easy_install-qvdkaj\MySQL_python-1.2.5-py2.7-win32.egg.tmp\MySQLdb\connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on 'localhost' (10061)")

2017-12-24 21:07:55,516 - DaoDecorator - 5660 - ERROR - read - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\core\DaoDecorator.py", line 31, in read
    return DbBaseHelper().read(sql,self.data)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseHelper.py", line 21, in read
    db = Connection(autocommit=False)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 32, in __init__
    self.reconnect(**dbinfo)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 67, in reconnect
    self._conn = self._get_connection(**kwargs)
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\util\dbUtil\dbBaseUtil.py", line 70, in _get_connection
    return MySQLdb.connect(cursorclass=MySQLdb.cursors.DictCursor, charset = 'utf8', **kwargs)
  File "c:\users\jessica\appdata\local\temp\easy_install-qvdkaj\MySQL_python-1.2.5-py2.7-win32.egg.tmp\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "c:\users\jessica\appdata\local\temp\easy_install-qvdkaj\MySQL_python-1.2.5-py2.7-win32.egg.tmp\MySQLdb\connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on 'localhost' (10061)")

